### ISSUE TITLE
[idea] Thiner scrollbar with compatibility with color palette

### ISSUE THREAD

**Issue by kookma** [crazko/krystal#25]
The inner scrollbars are thick and not compatible with palette color. A stylesheet can be used to set the scrollbar thickness and possibly to follow the color palettes.

See:

https://github.com/Jermolene/TiddlyWiki5/discussions/5352#discussioncomment-262490

**Comment by crazko** [comment]
Hi, thanks for your suggestion. Scrollbars adhere to your OS design and in most cases I like them to look just like that.

Also, I'd like to keep design of this plugin as minimal as possible and rather let users to make their own choices. That's why my own TiddlyWiki is different to default Krystal styling :)

Luckily, it's easy to [add your own styles](https://tiddlywiki.com/#Using%20Stylesheets) and meet your needs :)

**Comment by kookma** [comment]
@crazko - Yes, but it is not what most users can do! Custom styling specially for scrollbars needs a good understanding of CSS technology!

By the way thank you for replying!
